### ISSUE TITLE
get.data.celltype incorrectly parses the columns`

### ISSUE THREAD

**Issue by djinnome** [PNNL-CompBio/SERGIO#6]
According to the SERGIO README:

> Now each row represents a gene and each column represents a simulated single-cell. 
> Gene IDs match their row in this expression matrix, also cell types are groupd by columns such that the first 
> #cells_per_type columns correspond to the first simulated cell type, the next #cells_per_type columns correpond to 
> the second cell type and ... .

since each type corresponds to a bin,  I read this as saying if there are 300 cells per type, the first 300 columns correspond to the first bin, the second 300 columns correspond to the second bin, etc.

Please check my logic and let me know if you agree.

**Comment by NarmadhaMM** [comment]
You are right Jeremy. We got this wrong. According to Sergio the first 300 columns corresponds to cell type 1, second 300 to cell type 2 , and so on. Just pushed the updated files to github rerunning the analysis. The proportion of conditional independencies that we couldn't verify (statistically proven as dependent) are around 55%-60% now.

**Comment by NarmadhaMM** [comment]
The results are exactly same using the DS1.dagitty file. I think there is variability from cell types , and probably one data set may not be enough to come to a conclusion.
